# Generated by Django 5.1.7 on 2025-04-16 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trip_title", models.CharField(max_length=255)),
                ("trip_description", models.TextField(blank=True)),
                ("trip_destination", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "trip_visibility",
                    models.CharField(
                        choices=[("private", "Private"), ("public", "Public")],
                        default="private",
                        max_length=10,
                    ),
                ),
                (
                    "trip_image",
                    models.ImageField(blank=True, null=True, upload_to="trip_images/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trip_organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organized_trip",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "trip_participants",
                    models.ManyToManyField(
                        blank=True,
                        related_name="joined_trips",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
