# Generated by Django 5.1.7 on 2025-04-17 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0004_tripjoinrequest"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tripuserrelation",
            old_name="trip_id",
            new_name="trip",
        ),
        migrations.RenameField(
            model_name="tripuserrelation",
            old_name="user_id",
            new_name="user",
        ),
    ]
