# Generated by Django 5.1.7 on 2025-04-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0005_rename_trip_id_tripuserrelation_trip_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="public_token",
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
    ]
