# Generated by Django 5.1.7 on 2025-04-17 20:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0006_trip_public_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="public_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
