# Generated by Django 5.1.7 on 2025-04-17 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0007_alter_trip_public_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trip",
            name="public_token",
        ),
    ]
