# Generated by Django 5.1.7 on 2025-04-17 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0008_remove_trip_public_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="public_token",
            field=models.UUIDField(editable=False, null=True, unique=True),
        ),
    ]
